### ISSUE TITLE
关于轴板在键盘外壳上的分布问题

### ISSUE THREAD

**Issue by A-new-b** [Dimsmary/Dactyl-HelloWord#1]
您好，我对您的键盘方案十分感兴趣，目前正在按照您提供的方案制作键盘，但我目前遇见了一个问题。

您提到了轴板有三种类型，分别为U1,U2,U3,对应4pin,5pin,6pin,在外壳上，我并不清楚单独的一个格子对应的是u1,u2还是u3,
![图片](https://user-images.githubusercontent.com/43344034/203038964-74098369-a4cc-4e4e-ad9b-5fca0dcb2eba.png)

我确实已经反复看过您的视频和立创文件，目前卡在了这一步，希望您能给我一个解答，感激不尽！

**Comment by Dimsmary** [comment]
不好意思，轴板的连接比较复杂，文档还有待完善。
左手的轴板连接如图所示，如果有任何疑问欢迎继续提出。
![left_board_pcb](https://user-images.githubusercontent.com/35646719/203061985-2aa3d3bd-d2ad-41de-97d6-2e70d152ff63.jpg)

**Comment by Dimsmary** [comment]
不好意思，轴板的连接比较复杂，文档还有待完善。
左手的轴板连接如图所示，右手轴板排布基本相同，如果有任何疑问欢迎继续提出。
![Left_board_pcb](https://user-images.githubusercontent.com/35646719/203062857-209d21bb-c09e-4b30-b0f7-4723eca76bf8.jpg)

**Comment by A-new-b** [comment]
非常感谢，我参照原理图和您的轴板后基本明白了
